title: Andreas Zeijlon # your name (or website title) here
logo: "/images/profile-picture.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hello, my name is Andreas and I'm an aspiring developer with special interest in web and game development. I'm soon graduating as M.Sc. in Computer Science and Engineering with focus on security and programming.
  <br><br>

  <a href="https://www.linkedin.com/in/andreas-zeijlon-917982151/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
